### ISSUE TITLE
Integração da página do medicamento com Categorização (RxNorm)

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/medlist#14]
Documentação da API https://rxnav.nlm.nih.gov/RxNormAPIs.htm

**Comment by renatomurasaki** [comment]
Integrar os metadados do serviço https://rxnav.nlm.nih.gov/ referente aos blocos de informação de brand / branded drug (lado direito da tela).

O título da aba poderia ser "Medicamentos comercializados (Fonte: RxNav - NIH / US NML)"

**Comment by renatomurasaki** [comment]
Utilizar as chaves para API: SCD/GPCK e SBD/BPCK

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/medlist/commit/a0e0f50b2b7382a4f73612a098f17b7fea78c14e

**Comment by renatomurasaki** [comment]
Manter os títulos "Branded Drug or Pack" e "Clinical Drug or Pack" fora da ação de scroll down/up


________________________________
De: viniciusandrade <notifications@github.com>
Enviado: quinta-feira, 15 de agosto de 2019 16:25
Para: bireme/medlist <medlist@noreply.github.com>
Cc: Renato Murasaki <renato.murasaki@gmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [bireme/medlist] Integração da página do medicamento com Categorização (RxNorm) (#14)


Implementado em a0e0f50<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fmedlist%2Fcommit%2Fa0e0f50b2b7382a4f73612a098f17b7fea78c14e&data=02%7C01%7Cmurasaki%40paho.org%7C58310b15d8e74270689d08d721b65de0%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637014939455870162&sdata=Af1E6RVAcbDH9Fkt2tTppyVeJKupufQUThn2%2B%2BTPcqY%3D&reserved=0>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fmedlist%2Fissues%2F14%3Femail_source%3Dnotifications%26email_token%3DAAJLL2WIP7ELGGS2JNPFPYTQEWUTNA5CNFSM4HOUVEKKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4MYFQY%23issuecomment-521765571&data=02%7C01%7Cmurasaki%40paho.org%7C58310b15d8e74270689d08d721b65de0%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637014939455880155&sdata=FvlFjI3Fz0QG9Z00%2BywEW3pjK%2BAjft494Sk58DS4%2F%2Fw%3D&reserved=0>, or mute the thread<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAJLL2XWDJ6AN53URX5CR7DQEWUTNANCNFSM4HOUVEKA&data=02%7C01%7Cmurasaki%40paho.org%7C58310b15d8e74270689d08d721b65de0%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637014939455880155&sdata=NVrlZmolWeU4b4XBW4NuYp%2BetmcgrZ6VWA7HBVYzoG4%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by viniciusandrade** [comment]
Ajuste aplicado no layout.
